export async function seed(knex) {
  await knex("question").del();
  await knex("question").insert([
    {
      id: 1,
      quiz_id: 1,
      question_nl: "Wat weet je over de oren van een dolfijn?",
      question_en: "What do you know about the ears of a dolphin?",
      question_fr: "Que savez-vous des oreilles d'un dauphin ?",
      image_url: "q1.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      quiz_id: 1,
      question_nl: "Wat is sonar?",
      question_en: "What is sonar?",
      question_fr: "Qu'est-ce que le sonar ?",
      image_url: "q2.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      quiz_id: 1,
      question_nl: "Is een dolfijn een solitair dier?",
      question_en: "Is a dolphin a solitary animal?",
      question_fr: "Le dauphin est-il un animal solitaire ?",
      image_url: "q3.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 4,
      quiz_id: 1,
      question_nl: "Zitten er botten in de vinnen van dolfijnen?",
      question_en: "Are there bones in the fins of dolphins?",
      question_fr: "Y a-t-il des os dans les nageoires des dauphins ?",
      is_active: true,
      image_url: "q4.png",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 5,
      quiz_id: 1,
      question_nl:
        "Hoe kun je het verschil zien tussen een mannetjes dolfijn of vrouwtjes dolfijn?",
      question_en:
        "How can you tell the difference between a male and female dolphin?",
      question_fr:
        "Comment faire la différence entre un dauphin mâle et une femelle ?",
      image_url: "q5.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 6,
      quiz_id: 2,
      question_nl: "Heeft een dolfijn oren?",
      question_en: "Does a dolphin have ears?",
      question_fr: "Un dauphin a-t-il des oreilles ?",
      image_url: "q1.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 7,
      quiz_id: 2,
      question_nl: "Wat is sonar?",
      question_en: "What is sonar?",
      question_fr: "Qu'est-ce que le sonar ?",
      image_url: "q2.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 8,
      quiz_id: 2,
      image_url: "q3.png",
      question_nl: "Is een dolfijn een solitair dier?",
      question_en: "Is a dolphin a solitary animal?",
      question_fr: "Le dauphin est-il un animal solitaire ?",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 9,
      quiz_id: 2,
      question_nl: "Zitten er botten in de vinnen van een dolfijn?",
      question_en: "Are there bones in the fins of dolphins?",
      question_fr: "Y a-t-il des os dans les nageoires des dauphins ?",
      image_url: "q4.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 10,
      quiz_id: 2,
      question_nl:
        "Hoe kan je het verschil zien tussen een mannetjes dolfijn of vrouwtjes dolfijn?",
      question_en:
        "How can you tell the difference between a male and female dolphin?",
      question_fr:
        "Comment faire la différence entre un dauphin mâle et une femelle ?",
        image_url: "q5.png",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]);
}
